### ISSUE TITLE
WCAG Greys

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/styleguidekit-assets-default#1]
Try out some WCAG colors just to see what might work in the new edition.

+@dcmouyard

**Comment by dcmouyard** [comment]
I recommend using http://leaverou.github.io/contrast-ratio and aim for a minimum contrast ratio of 7.

Are there specific color combinations you’re looking for?

**Comment by bradfrost** [comment]
We're talking for the nav bar and the list view? I'm definitely open to lightening the font size up a bit, but don't want to overpower the core content, which isn't Pattern Lab itself.

**Comment by bradfrost** [comment]
PL 2.0 launched `#808080` text on a `#000` background, which passes WCAG 2.0 AA. Additionally, a big refactor (see #72) will provide the ability to further customize the PL chrome.
