### ISSUE TITLE
'storefront' mode architecture?

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/styleguidekit-assets-default#104]
I'm beginning to think through how the [storefront](http://bradfrost.com/blog/post/the-workshop-and-the-storefront/) mode (essentially a style guide mode used for documenting patterns and documentation rather than for tinkering with pattern code) within Pattern Lab will work, and I'm writing this as a question/start of a conversation.

In essence, the style guide mode for a component detail will [look something like this](http://bradfrost.github.io/style-guide-guide/components/blocks-and-cards/card.html):

```
PATTERN TITLE
Pattern description and possibly some other stuff

[ LIVE PATTERN ]

Documentation and other stuff.
```

I'm finding that while a lot can be accomplished with only CSS modifications to PL's shell, there are a few areas that I think would require some significant changes to the markup and source order. 

So my question to @bmuenzenmeyer and @EvanLovely is: how do you see this happening? Is it possible to render a different template for the storefront compared to the workshop? Or do we have to get creative with what we already have? 

And one last-but-not-insignificant point is how to generate both versions? The thought is the workshop is the default, and then there would be a flag in the command to build out the storefront, which would consume a different (or subset) config file. Interested to hear from you how you think this would work.

**Comment by bmuenzenmeyer** [comment]
Hey Brad - thanks for starting this conversation - I definitely want to frame it up soon. I have a general outline in my head - hopefully you can stand to wait a few days?

**Comment by bradfrost** [comment]
@bmuenzenmeyer yeah, absolutely! Definitely interested in hearing your ideas. I'll do my best to draw out some of the ideas tumbling around in my head.

**Comment by bradfrost** [comment]
Closing this out as we're moving this to its own discussion over here: https://github.com/pattern-lab/the-spec/issues/38
