### ISSUE TITLE
Style Updates

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/styleguidekit-assets-default#11]
@bradfrost -

I've pushed the latest mark-up changes to `feature-panels` that you wanted. Now the modal pop-up and style guide view share the same layout. They're _not_ well-styled so they look a bit jumbled. I think I nuked a class that held things together better. Sorry.

To make changes to this you're going to need to get the latest development edition installed running the `feature-panels` branch of several repos. I realize this is annoying. I thought about emailing you an almost pre-built copy but realized I'd have to step you through updating your git config so... This is actually easier.
1. Figure out where you're going to install it
2. Run `composer create-project pattern-lab/edition-development feature-panels-work`
3. Wait for it to finish installing then...
4. `cd feature-panels-work/vendor/pattern-lab/core`
5. `git config branch.dev.remote origin`
6. `git checkout --track origin/feature-panels`
7. `cd ../styleguidekit-mustache-default` 
8. `git config branch.dev.remote origin`
9. `git checkout --track origin/feature-panels`
10. `cd ../styleguidekit-assets-default` 
11. `git config branch.dev.remote origin`
12. `git checkout --track origin/feature-panels`
13. `npm install`
14. `bower install`
15. `cd ../../../`
16. `php core/console -g`
17. `cd vendor/pattern-lab/styleguidekit-assets-default`
18. `gulp --copy-dist ../../../public`

Edit to your hearts content. Use `gulp --copy-dist ../../../public` to make sure everything goes where it needs to. The template for the modal pop-up can be found in `./src/html/partials/base-template.html`. I tried to break that up a little more for you.

Two classes that you can use differentiate styles between the modal and the style guide view are `.sg-view-container` and `.sg-pattern-extra`. Otherwise I think it's fairly self-explanatory. I tried to delete all of my unnecessary IDs.

**Comment by bmuenzenmeyer** [comment]
Really excited for this! Thanks for all the hard work so far Dave / Brad!

**Comment by bradfrost** [comment]
Awesome, thanks for this @dmolsen. I'm going to take a look later on today.

**Comment by bradfrost** [comment]
@dmolsen Thanks so much for the detailed instructions! I was able to get everything up and running.

Here's where I'm getting stuck. 
<img width="497" alt="pattern lab" src="https://cloud.githubusercontent.com/assets/383701/15527137/d64a6006-2205-11e6-884d-fe436d409956.png">

I'm not sure if there's something I'm doing wrong, but I'll try to dig in deeper.

**Comment by dmolsen** [comment]
@bradfrost -

I guess I skipped a step. 18 should have been `gulp --copy-dist ../../../public`. The `feature-panels` work needs to be copied to `./public` at least once. Then you should be good to go.

**Comment by bradfrost** [comment]
YES! Alright I'm up and running. Time to style some stuff.

**Comment by bradfrost** [comment]
@dmolsen scratching my head on this. I'm looking to add a class to the pattern title. It's rendering on the frontend as an `<h3>` but can't find an `<h3>` anywhere in the file system. 

Looking at `base-template.html`, I see this:

```
<div class="sg-pattern-head">
      <h2>{{ patternName }}</h2>
     ...
```

But making changes to that doesn't do anything. Any ideas on where I should be editing?

**Comment by dmolsen** [comment]
You should edit the only code that's _not_ in StyleguideKit assets. It's in `vendor/pattern-lab/styleguidekit-mustache-default/`. I think it's `patternSection.mustache`.

**Comment by bradfrost** [comment]
Awesome thanks!

**Comment by bradfrost** [comment]
Alright, I've pushed my initial style changes to the panels, but ended up adding a whole slew of comments to the CSS and refactored a few things along the way. 

@dmolsen, on the pattern detail pages I'm not able to get the pattern info to show up. I'm guessing it's because I messed with some of the structure and naming in `base-template.html`. Before there were a few floating `<div>`s floating around without any classes or anything, and when I removed them the info stopped appearing. We probably want to revisit that to make sure things are functional but also named properly.

Once we get that working, I can finish the detail modal, finish up the rest of the CSS comments, and tackle annotations then we should be good to go from a UI perspective!

**Comment by dmolsen** [comment]
@bradfrost -

Looks like I was hooking into the outermost `div` to do some manipulation/insertion. I can build that in JS instead. That would be cleaner. Will do that today.

**Comment by dmolsen** [comment]
@bradfrost -

I've built that extra `div` into the JS proper. Please do a `git pull` and `gulp --copy-dist ../../../public`.  Thanks.

**Comment by bradfrost** [comment]
@dmolsen @bmuenzenmeyer Alright, here's an update on the UI code. Right now, here's what the pattern info panel looks like on the view all page:

<img width="761" alt="pattern lab" src="https://cloud.githubusercontent.com/assets/383701/15683559/0d53244a-2731-11e6-8aa9-e266bff4f212.png">

A few notes:
- The tabs for the code panels need to match the Prism code highlighting. So if we decide to switch the code styles from light to dark (I believe it was dark not that long ago?), we'll have to update the tab styles as well.
- I moved the pattern state beside the title (as per #19)
- I haven't tested the pattern description with a real instance yet. I created some lorem ipsum in the meantime. How would I go about making sure that's displaying properly.
- And last one — the big one — is that I'm not able to get the pattern info to appear on the pattern detail modal. @dmolsen any ideas about that? I know you said you were generating a div via JS, so I don't know if that's influencing its display. If you could add a `className` to the generated `div` so that I know what that's doing, that would help. 

I'm going to assign this to @dmolsen to address the modal style info. Once we have that info showing up I'll style it and then I believe we're good to go.

**Comment by bmuenzenmeyer** [comment]
I love the progress Brad! Thanks for sharing. A couple questions / comments:
- Ccan the code view indentation be shortened to reduce horizontal whitespace?
- I've worried about what this looks like with longer pattern descriptions? Sounds like you wonder that too, alluding to not running against actual data. It depends I guess with how content people want to annotate patterns with I suppose.
- Are code description/lineage (left side) and codeview (right side) independently scrollable? I cannot remember from my test rig at home.

> And last one — the big one — is that I'm not able to get the pattern info to appear on the pattern detail modal. @dmolsen any ideas about that? I know you said you were generating a div via JS, so I don't know if that's influencing its display. If you could add a className to the generated div so that I know what that's doing, that would help.

I don't think I've gotten this working either, FWIW.

cc @geoffp look, it's alive! the long-promise UI we dreamed of :+1:

**Comment by bradfrost** [comment]
@bmuenzenmeyer 

> Can the code view indentation be shortened to reduce horizontal whitespace?

Good question. I'm not sure how the Prism stuff works and also don't know if there's a way to sanitize that code before it gets injected into the UI. @dmolsen, any ideas?

> I've worried about what this looks like with longer pattern descriptions? Sounds like you wonder that too, alluding to not running against actual data. It depends I guess with how content people want to annotate patterns with I suppose.

Here's a rough idea of what that would look like:

<img width="1141" alt="window" src="https://cloud.githubusercontent.com/assets/383701/15684948/8cdc9998-2737-11e6-900d-0dc9d46ab129.png">

I've flexboxed the code panels to stretch to the height of the container, so if there's more code and there's room to show it, it shows.

> Are code description/lineage (left side) and codeview (right side) independently scrollable? I cannot remember from my test rig at home.

Related to above. Basically the height of the info panel will expand with the left column, and the code will flex to match the height. This will be handled differently on the detail pages due to the modal, and yes, those panels will be independently scrollable, especially if we're handling annotations in there.

**Comment by bmuenzenmeyer** [comment]
@bradfrost thanks for the quick response and demo. I think this is acceptable. Let people be as verbose as they want.

**Comment by bmuenzenmeyer** [comment]
> Good question. I'm not sure how the Prism stuff works and also don't know if there's a way to sanitize that code before it gets injected into the UI. @dmolsen, any ideas?

is it controllable via https://developer.mozilla.org/en-US/docs/Web/CSS/tab-size ???

**Comment by dmolsen** [comment]
> Good question. I'm not sure how the Prism stuff works and also don't know if there's a way to sanitize that code before it gets injected into the UI. @dmolsen, any ideas?

Not sure what's meant by "sanitizing code". The [Prism.js docs](http://prismjs.com) in case there's anything there to help with styling features. It's just CSS so I think inspecting it will give you all an idea of what you might want to change to get the look you want.

> I haven't tested the pattern description with a real instance yet. I created some lorem ipsum in the meantime. How would I go about making sure that's displaying properly.

If you want to add a description for `00-colors.mustache` simply create a `00-colors.md` and add the following:

```
---
title: Color Swatch
---
This is a *strong description* about colors and what not.
```

> And last one — the big one — is that I'm not able to get the pattern info to appear on the pattern detail modal.

This isn't working locally for me anymore either. Not sure what I did. Revisiting now.

**Comment by bradfrost** [comment]
@bmuenzenmeyer thanks for the tips re: `tab-size`. That and some `display` settings did the trick. What do you think of this?

<img width="883" alt="pattern lab" src="https://cloud.githubusercontent.com/assets/383701/15686276/8881efc8-273d-11e6-95fc-7b031b83a042.png">

I set `tab-size: 2`, but we can adjust it to whatever we want. Like 17.

<img width="883" alt="pattern lab" src="https://cloud.githubusercontent.com/assets/383701/15686307/b2d33de0-273d-11e6-8a83-5619880d2775.png">

**Comment by dmolsen** [comment]
+1 on 17.

**Comment by bradfrost** [comment]
@dmolsen question about the pattern description: does it support markdown? As in, can there be paragraphs, links, bold, italic, etc in there?

**Comment by dmolsen** [comment]
@bradfrost -

Yup. It's a markdown file with YAML front matter (_the bit between `---`_).

**Comment by bmuenzenmeyer** [comment]
AFAIK, last check of `edition-node-gulp` this weekend, description was parsing markdown into `{{{patternDesc}}}`

and I think 17 works for `tab-size` too :wink:

**Comment by geoffp** [comment]
Guys, this looks great! Can we have a disco mode for indentation? Just whiplash back and forth between zero and 17.

Joking aside, this two-column tabbed layout is so comfortable that I almost want it to be open by default.

**Comment by dmolsen** [comment]
@geoffp - 

Have @bmuenzenmeyer add a config option to the spec ;) It's not a bad idea.

**Comment by bradfrost** [comment]
@dmolsen @geoffp @bmuenzenmeyer Perhaps the option could persist similar to the viewport size. Once the pattern info panels are opened, they'll stay open even if the page is refreshed.

**Comment by bmuenzenmeyer** [comment]
> Have @bmuenzenmeyer add a config option to the spec ;) It's not a bad idea.

will add - I now have 6 things to bring up when I get time :clock1:

**Comment by dmolsen** [comment]
@bmuenzenmeyer -

Not exactly critical ;)

**Comment by dmolsen** [comment]
@bradfrost -

In `styleguidekit-assets-default` try another `git pull` and `gulp --copy-dist=../../../public`

**Comment by geoffp** [comment]
Yeah, not important but it makes me want to write up a thing with real UX personas based on the different kinds of people that look at our rather large and poorly documented pattern library. It would be interesting to think through what they need and how they get it.

**Comment by bradfrost** [comment]
@dmolsen awesome it's showing up now! Stay tuned.

**Comment by bradfrost** [comment]
Alrighty, status update on the modal styles: 

![pattern lab - molecules-media-block](https://cloud.githubusercontent.com/assets/383701/15695517/0a4b24f6-2776-11e6-8490-a4ccd8fd926d.png)
- The two panels are independently scrollable, so if you have a crazy long description you can scroll through that while still seeing the whole code block. 
- I added an 'X' icon instead of the 'Close' text label to match with the icon in the top. I also moved it out of the way of the rest of the modal so the content inside can scroll while the close button stays fixed.
- I left the code coloring as is. I like the contrast and think it's easier not to overcomplicate things too much.

So that's pretty much that.

**Comment by bmuenzenmeyer** [comment]
This is great! One minor thing I noticed at one point was it was hard to
copy all code to paste.  This is sometimes tricky cross browser without
flash or the like... but some libraries exist.  Is this a feature to
support?

**Comment by dmolsen** [comment]
Two thumbs up, Brad. Nice job.

I'm open to "click to copy" but you're right it involves a bit to get it to work. PRs welcome.

My solution had been supporting a select all and then a user can use regular copy. That's not currently in feature-panels since it was a rewrite and I was focused on getting brad through styling.

**Comment by bradfrost** [comment]
> One minor thing I noticed at one point was it was hard to
> copy all code to paste.  This is sometimes tricky cross browser without
> flash or the like... but some libraries exist.  Is this a feature to
> support?

I'd say that's a nice to have feature. Not critical to get 2.0 out the door, but worth throwing up as an issue.

**Comment by bmuenzenmeyer** [comment]
This looks promising https://clipboardjs.com/ but I agree with Brad - a separate issue is smart.

Created https://github.com/pattern-lab/styleguidekit-assets-default/issues/20

**Comment by dmolsen** [comment]
I have two more style issues that need to be addressed. Sorry.

### Panel Toolbar

The first would be we need a way to have a simple toolbar inside a panel. So if we were to do #20 the button needs someplace to live. Also, with annotations as a panel we need a way to fire off "show them numbered on the pattern" like how it works now. @bradfrost , you can just mock-up a three item list inside [this div](https://github.com/pattern-lab/styleguidekit-assets-default/blob/0f800c48c25126d07998fd89c712911b3032e004/src/html/partials/base-template.html#L69-L71) and I'll figure out how to populate it via the Panels JSON config. I figure it'd just run horizontal like:

```
Copy to clipboard | Click to say you're awesome | Cool Shit Happens with you click this
```

### Subtype Documentation

One of the hidden features of PL/PHP is the ability to add documentation for subtype sections. For example, explaining the purpose of the atoms in the global subtype. Looks like I broke that when refactoring so I tried to put together some quick fixes. To enable this so you can style it do the following from the root of your project:
1. `cd vendor/pattern-lab/core`
2. `git pull`
3. `cd ../styleguidekit-mustache-default`
4. `git pull`
5. `cd ../../..`
6. Then create a file at `source/_patterns/00-atoms/01-global.md` and add a title and description
7. `php core/console -g`

The file you need to edit is `vendor/pattern-lab/styleguidekit-mustache-default/partials/patternSectionSubtype.mustache`

Example content for your `01-global.md` file:

```
---
title: Global Patterns
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus id urna id luctus. Quisque nisi diam, hendrerit eget diam ac, egestas dictum lectus. Nunc blandit tellus ut nulla aliquam, a fermentum quam accumsan. In eu nunc mollis erat venenatis pellentesque. Curabitur volutpat faucibus felis ut pellentesque. Donec et eros tempus metus consectetur efficitur. Pellentesque semper justo vestibulum bibendum ullamcorper.
```

**Comment by bmuenzenmeyer** [comment]
I did see references to those subtypes in type code somewhere.  Excited to
get that into PL/Node too soon!

**Comment by dmolsen** [comment]
@bradfrost -

Here's what I was thinking for the "toolbar" within a panel. I'm pretty sure I can populate it via JSON but I need the stubbed out mark-up and styles to work from. Thanks.
<img width="1005" alt="screen shot 2016-06-03 at 4 52 35 pm" src="https://cloud.githubusercontent.com/assets/2746/15792533/d151b3b2-29ab-11e6-94df-0b8679d75484.png">

**Comment by bradfrost** [comment]
@dmolsen Hmmm, alright. I think I see what you're getting at, but don't know if I'm on board with the placement of things.

Regarding the Copy to clipboard placement, I was thinking it would be more of a absolute positioned element that's commonly seen on code snippets. Something along the lines of [this](http://tutsplus.github.io/clipboard/).

As for the annotations, I feel like that information should be displayed in the left panel alongside the other text-based pattern info. I'm thinking left side = pattern info and right side = pattern code. Does that seem to make sense? If it's impossible to put the annotations in the left-hand column, let me know and we can work something else out.

**Comment by dmolsen** [comment]
@bradfrost -

Go ahead and create your mark-up for annotations on the left-side then. Because it's "core" i can work it a couple of different ways.

To be clear, panels can't/won't only be code. They're the only place I can create a hook to include content generated by plug-ins. KSS for example would be "text-heavy" as opposed to strictly code. We will end up with Mustache, HTML, KSS tabs after the someone installs the KSS plug-in. The left side of the modal can't just keep getting longer and longer even with an overflow scroll. At some point it feels like we'd end up burying useful information.

Also, when you create the mock mark-up make sure you put it in the order you like. So above or below the description. And decide if you want the annotation numbers to appear when someone clicks "Show Pattern Info" or if you want some other mechanism to control that. If it's another mechanism please place the mark-up in the template and I'll create the hook.

**Comment by dmolsen** [comment]
@bradfrost -

I fixed a couple of bugs. Please make sure to run `git pull` before working again. Thanks.

**Comment by bradfrost** [comment]
Heyo,
Sorry I'm just now getting around to answering.

> To be clear, panels can't/won't only be code. They're the only place I can create a hook to include content generated by plug-ins. KSS for example would be "text-heavy" as opposed to strictly code

Got it! Although I'd say KSS is related to code, I get the idea. Any extensions will appear over there. 

> The left side of the modal can't just keep getting longer and longer even with an overflow scroll. At some point it feels like we'd end up burying useful information.

Totally hear you. I have an idea on how to lay things out, so I'll put together a prototype so we can explore the options. Just letting you know my schedule this week is totally booked but I'm going to try to squeeze it in.

**Comment by bradfrost** [comment]
Alrighty, here's what I've come up with for styling the annotations:

![pattern lab - pages-homepage](https://cloud.githubusercontent.com/assets/383701/16085455/1df9e9fe-32ea-11e6-9d00-901a899e91c0.png)

Again, I feel like including annotations on the left is a good idea as it's very related to the pattern description and info. The idea is that switching on annotations would scroll that panel to the annotations section, and when the user clicks on a DOM element that has an annotation, it would jump the user to the appropriate annotation. @dmolsen, I added an `.active` style for a highlighted annotation with an example in `base-template.html`. 

Open to suggestions and tweaks, and @dmolsen let me know what else you need from me in order to bring this guy home!

**Comment by dmolsen** [comment]
> The idea is that switching on annotations would scroll that panel to the annotations section, and when the user clicks on a DOM element that has an annotation, it would jump the user to the appropriate annotation

This has me lost. How does someone "turn on annotations"? The only hook we have is "show pattern info." I figured that meant show annotations in the info area 100% of the time when the pattern info is shown. That's totally doable. The trick becomes when to toggle the numbers on in the pattern view. You could add a "show" link next to the "Annotations" title or similar which would toggle that.

Otherwise it looks fine to me.

**Comment by bradfrost** [comment]
> The only hook we have is "show pattern info." I figured that meant show annotations in the info area 100% of the time when the pattern info is shown. That's totally doable.

Ah yeah, my bad. Yep, I think displaying annotations with the rest of the documentation by default is a great way to go. Forgive me, I was still thinking in PL1 terms.

**Comment by dmolsen** [comment]
@bradfrost -

I noticed in your new annotations block that we don't need titles. In PL1 it's:

```
1. Title for element 1
Comment for element 1

2. Title for element 2
Comment for  element 2
```

In the latest push to `feature-panels` it's:

```
1. Comment for element 1
2. Comment for element 2
```

If we're ditching titles then Brian and I need to update code/docs. It's not a huge issue from a code perspective because we can silently ignore the attribute. From a docs/workshop perspective we'll want to get that nailed down.

Also, in reference to "we're going to show annotations all the time" from the email thread I'll just show the numbers on the pattern itself with no way to toggle that on or off. I'm just going to keep moving forward on this.

**Comment by bradfrost** [comment]
@dmolsen ah, apologies on the lack of title. Let's do:

```
<li><strong>Title for element 1</strong> — Comment for element 1</li>
<li><strong>Title for element 2</strong> — Comment for element 2</li>
```

We'll keep them inline with the rest of the text.

> Also, in reference to "we're going to show annotations all the time" from the email thread I'll just show the numbers on the pattern itself with no way to toggle that on or off. I'm just going to keep moving forward on this.

Sounds good!

**Comment by dmolsen** [comment]
@bradfrost -

All of these changes are now in `dev`. If you want to see them I think it's easiest to start fresh. Brian and I made a big change with `styleguide-specific.css` and it's just easier to go brand-new.
1. Figure out where you're going to install it
2. Run `composer create-project pattern-lab/edition-development dev-review`
3. Wait for it to finish installing then...
4. `cd dev-review/vendor/pattern-lab/core`
5. `git config branch.dev.remote origin`
6. `cd ../styleguidekit-mustache-default` 
7. `git config branch.dev.remote origin`
8. `cd ../styleguidekit-assets-default` 
9. `git config branch.dev.remote origin`
10. `npm install`
11. `bower install`
12. `cd ../../../`
13. `php core/console -g`
14. open a new tab in terminal and type `php core/console -s` to get the built-in Pattern Lab server going. follow those directions

If you want to edit the iFrame wrapper code do the following:
1. Open `vendor/pattern-lab/styleguidekit-assets-default` in your favorite editor
2. _make changes_
3. `cd vendor/pattern-lab/styleguidekit-assets-default`
4. `gulp --copy-dist ../../../public` (_you can add `--watch` if you want to_)

If you want to edit the "view all" view that shows up _in_ the iFrame (e.g. title for the section listing) do the following:
1. Open `vendor/pattern-lab/styleguidekit-mustache-default/views` in your favorite editor
2. _make changes_
3. `php core/console -g`

I thing that the latter needs some stylistic touch-up. It doesn't feel like it has any sort of visual organization. Also, please remember [my earlier comment](https://github.com/pattern-lab/styleguidekit-assets-default/issues/11#issuecomment-223059881) that a user can add subtype documentation. I gave you an example. That might need styling too.

**Comment by bradfrost** [comment]
@dmolsen this is awesome news! Congrats.

> I thing that the latter needs some stylistic touch-up. It doesn't feel like it has any sort of visual organization. Also, please remember my earlier comment that a user can add subtype documentation. I gave you an example. That might need styling too.

"The latter" refers to the "view all" view? I'm having a hard time visualizing this. It's gonna be a bit late for me to get to this, but I'll pull this down later tonight.

**Comment by dmolsen** [comment]
@bradfrost -

Yeah, the "view all" view. I think it'll make more sense once you try to scroll through it. Also forgot to mention that I had to tweak the layout of annotations a little bit more. We had `<p></p>` tags in the description. This was in `annotations.js` plus when annotations are generated from Markdown files. Not a big issue. It's just now:

```
1. Title
   Description
```

Again, should make sense when you see it. There are a couple of style quirks throughout. For example, if a pattern has annotations but no lineage you end up with two lines between the description and annotations. I don't think these issues need to be fixed tonight.

**Comment by bradfrost** [comment]
Closing this out
