### ISSUE TITLE
Add "Publish Release" doc

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/styleguidekit-assets-default#17]
Add a `./docs` dir and document how to push a release so PHP and Node can take advantage of it.

**Comment by sbubaron** [comment]
Is this related to github pages? If so I just changed the config to output to /docs instead of /public -- seems to be working: https://github.com/SBUDoIT/unity-lab-node / https://sbudoit.github.io/unity-lab-node/

**Comment by bradfrost** [comment]
Closing this issue
