### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/styleguidekit-assets-default#18]
I believe it's because the HTML element is using a class of `sg-find` and the JS in `src/pattern-finder.js` is looking for an ID of `sg-find`. When I change `#sg-find` to `.sg-find` in that file (and recompile and place those files in the appropriate place in `public/`) I get this error after clicking in the search field in the console:

```
Uncaught RangeError: Maximum call stack size exceeded.
```

**Comment by bmuenzenmeyer** [comment]
I'll have to double check, but I thought search was working for me on the
feature-panel branch. Have you tried that yet Evan?

Checked... at one point I had tested it successfully.
https://github.com/pattern-lab/edition-node-gulp/issues/2

**Comment by bmuenzenmeyer** [comment]
Double-checked this morning. Working as expected since https://github.com/pattern-lab/edition-node-gulp/issues/14 was commented on. `feature-panels` branch

**Comment by dmolsen** [comment]
LOL. Just fired this up too, @bmuenzenmeyer . Yup, working in `feature-panels` so we'll have to wait on that for a fix. Brad is working on styles in support of #11. I still need to do #13 and #12 for that to be completely ready. Sorry, @EvanLovely .

**Comment by EvanLovely** [comment]
No worries; added issue to bring awareness to it more than anything. As long as the fix is in the pipeline I'm happy! 😀👍🏼
