### ISSUE TITLE
Move Pattern State Beside Title

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/styleguidekit-assets-default#19]
@dmolsen,
Question: how hard would it be to move pattern status to be beside the pattern title, like so:

<img width="1154" alt="pattern lab" src="https://cloud.githubusercontent.com/assets/383701/15561434/c76c4ef0-22c3-11e6-8ce8-f544c34ea9c9.png">

Hard? 

The thinking is that if people are using the pattern state feature, it would be good to have that info at-a-glance in scroll view. It also frees up space for pattern description and lineage in the actual `sg-patter-extra-info` section.

**Comment by dmolsen** [comment]
Not hard. I think you can put the following in styleguidekit mustache:

```
{{# patternState }}
  <div><span class="sg-pattern-state {{ . }}">{{ . }}</span></div>
{{/ patternState }}
```

Let me know how that works out for you. If it works then add it to the `{{# isPatternView }}...{{/ isPatternView }}` block in styleguidekit assets base-template so it's consistent.

**Comment by bradfrost** [comment]
Alright awesome I'll give that a shot!

On Thursday, May 26, 2016, Dave Olsen notifications@github.com wrote:

> Not hard. I think you can put the following in styleguidekit mustache:
> 
> {{# patternState }}
>   <div><span class="sg-pattern-state {{ . }}">{{ . }}</span></div>
> {{/ patternState }}
> 
> Let me know how that works out for you. If it works then add it to the {{#
> isPatternView }}...{{/ isPatternView }} block in styleguidekit assets
> base-template so it's consistent.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/pattern-lab/styleguidekit-assets-default/issues/19#issuecomment-221878014

## 

---

Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by bradfrost** [comment]
FYI, I've moved this beside the title and committed it. Unfortunately I'm not able to get it to appear, so I'm going to assign it to you to see why that's happening.

**Comment by dmolsen** [comment]
it'd be good if i was setting `patternState`. please do a `git pull` in `vendor/pattern-lab/core`. then run a `php core/console -g`.

**Comment by bmuenzenmeyer** [comment]
I think this is done unless more styling needs to occur

**Comment by bradfrost** [comment]
Yep I think that's good to go.
