### ISSUE TITLE
Implement Copy to Clipboard Support for Code View Panes

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#20]
As a designer/developer, I'd like to be able to quickly copy/paste pattern HTML or template code, so that I may more easily use the pattern in other systems.

---

https://clipboardjs.com/ looks like an option with some nice HTML-based declarative set of options or an API. Good browser support too.

**Comment by bradfrost** [comment]
I've implemented this for other projects, so will bring that functionality into PL

**Comment by bmuenzenmeyer** [comment]
I should add that https://github.com/roydanenterprises/plugin-node-clipboard exists in this space right now, and would likely be obsoleted if this feature would be built into the frontend

**Comment by bradfrost** [comment]
Oh yeah. I think that functionality makes sense as a core PL feature, and yep I think it makes sense to bake that into the frontend.

**Comment by bmuenzenmeyer** [comment]
the less code we have the better 

kill it with 🔥

**Comment by bradfrost** [comment]
We used this on a big design system project and it worked like a charm: https://clipboardjs.com/

**Comment by bmuenzenmeyer** [comment]
yup that's what my plugin uses. no reason why it couldnt be baked right in 🍰

**Comment by frostyweather** [comment]
Added clipboard.min.js library to PL. Added clipboard functionality to the code on both the single pattern page and the viewall (within the iframe).
![pattern-copy](https://user-images.githubusercontent.com/13662843/34850291-3f0b8e62-f6f3-11e7-8bec-9ebe31f257e5.gif)

**Comment by frostyweather** [comment]
And the view 
![pattern-copy-viewall](https://user-images.githubusercontent.com/13662843/34850385-8d60d16c-f6f3-11e7-9a8c-03bdaf1b116e.gif)
all mode

**Comment by frostyweather** [comment]
I think the only thing left to do with this is change the "Copied" text back to "Copy" when another copy button is clicked so the user isn't confused

**Comment by frostyweather** [comment]
Alright, made sure the only copied content had copied for the button text. The rest change back to Copy. This is within `feature-pattern-info-panel` branch

**Comment by bmuenzenmeyer** [comment]
Great work @frostyweather - I will merge this asap.

**Comment by bradfrost** [comment]
@bmuenzenmeyer Worth pointing out I'm going to do some style cleanup on this, but that will likely just be touching CSS.

**Comment by frostyweather** [comment]
@bmuenzenmeyer @bradfrost These have been styled properly now. This can be merged into develop now @bmuenzenmeyer
