### ISSUE TITLE
Style enhancement: Collapse sg-pattern-extra-info when no info present

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#21]
I have a suggestion for consideration to the frontend.
When a pattern does not have lineage, or a description, it would be nice if the code view could oocupy all available pattern info space.

![image](https://cloud.githubusercontent.com/assets/298435/15712192/06460e14-27d7-11e6-9a02-968d86144a64.png)

This should be achievable with CSS alone, using [:empty](http://caniuse.com/#feat=css-sel3) and the following styling:

![image](https://cloud.githubusercontent.com/assets/298435/15712222/1f5a71a6-27d7-11e6-9c0f-53432f9e5629.png)

I am willing to submit a PR for this, but first wanted to check with @bradfrost to get an up/down vote on appropriateness.

**Comment by bradfrost** [comment]
Yep I agree, and was trying to do that on my end. I'm just not sure what Mustache code to wrap things in. 

Essentially, we'd need to wrap the `sg-pattern-extra-info` div in a condition that would display false if no description or lineage exists. We'd then change `.sg-pattern-extra-code`'s styles to remove `width: 60%`. That should be it.

**Comment by bradfrost** [comment]
Unfortunately, `:empty` doesn't work because of the carriage returns. If I could figure that out, we could do it purely in CSS.

**Comment by bmuenzenmeyer** [comment]
hmm - maybe i'm just missing something on my end then, or devtools is giving me false positives, because applying the following directly to `sg-pattern-extra-info`

``` css
width: 0;
padding: 0;
```

does appear to allow `.sg-pattern-extra-code` to `flex` to the full width, despite having a declared with of 60%

I'll admit though I didnt actually fire this up locally with a proper `:empty` selector :frowning: 

sounds like we need a heavier-handed solution as you allude to

**Comment by bradfrost** [comment]
Would have to set it to `display: none`. If an item is flexed, the `width` property behaves differently.

**Comment by bmuenzenmeyer** [comment]
`.sg-pattern-extra-inner` looks to stretch it's children. `display: none;` works too :+1: 

Sounds like you are okay with the idea in concept, so if you don't get to it by Friday I will try to code something and submit a PR for review then.

**Comment by dmolsen** [comment]
This should be fixed. There was a `descBlockExists` check in the template but I wasn't properly setting it. I've fixed that so it is set to false when appropriate. `git pull && gulp --copy-dist=../../../public` should make it work the way folks expect it to. Someone double-check me and then we can close.

**Comment by dmolsen** [comment]
Welp, that sort of mucks with the pop-up modal. I'll add a fix for that so it works in both places.

**Comment by dmolsen** [comment]
Try 2 pushed.

**Comment by bmuenzenmeyer** [comment]
I can check later if no one gets to it

**Comment by bmuenzenmeyer** [comment]
This looks fixed per a65ab5d5ff921d32851b66430ad567a07b8aa05e and 0f800c48c25126d07998fd89c712911b3032e004 thanks @dmolsen
