### ISSUE TITLE
Show Pattern Info Toggle Does Not Close All Patterns' Pattern Info Panes

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#22]
Once you use the top-right gear menu to display every pattern's pattern info, the same control should toggle them all closed again. This does not occur, and no js errors fire.

Confirmed with @dmolsen 

I will have time to look at this Friday 6/3 if not resolved by then.

![image](https://cloud.githubusercontent.com/assets/298435/15712639/c246f82a-27d8-11e6-9b09-5cf1e354137f.png)

**Comment by bmuenzenmeyer** [comment]
Sorry closed the wrong issue

**Comment by dmolsen** [comment]
There's no code that actually closes those panels so... yeah, it's not going to work. I had the pop-up modal covered but not the patterns. I need to pass an event to the iframe that will do this. So on my TODO list.

**Comment by dmolsen** [comment]
Just committed this to `feature-panels`. Nav also toggles wording now. Double-check me please.

**Comment by bmuenzenmeyer** [comment]
@dmolsen confirmed, works.
