### ISSUE TITLE
Cannot select/focus `<input>`s and `<select>`s within PL iFrame

### ISSUE THREAD

**Issue by andrewnorell** [pattern-lab/styleguidekit-assets-default#24]
Hi there — thanks for working hard on various new iterations of PatternLab, particularly the Gulp edition!

I noticed a bug with my `<select>` and `<input>` elements, only when they were being accessed via the PatternLab iFrame. I couldn't seem to select them or get them to keep focus when clicking on them.

I tracked down the issue to the `body[0].onclick` function that starts at line 50 within `/src/js/postmessage.js`. 

I forked this repo and commented out that functionality, and my issue was resolved. I thought I'd mention it in case it's helpful to point out as a bug.

Thanks again for PatternLab, I love using it!

**Comment by dmolsen** [comment]
@andrewnorell -

Did you use any flavor of PL1 and do something similar with select/input? Is the select/input vanilla or have you attached JS to the elements? This bit of code has been around for years. I'd like to keep it but maybe I need to figure out a way to scope it a little bit better. Thanks.

**Comment by andrewnorell** [comment]
@dmolsen — great questions, thanks! I'll try doing separate, fresh installs of edition-node-gulp and patternlab-node, and see if I can consistently recreate the issue, just to make sure it's not something awry with my current project.

**Comment by andrewnorell** [comment]
@dmolsen - I was able to recreate the issue just now, on a fresh vanilla install of edition-node-gulp, with no code of my own. 
Here's the steps I took:
- `git clone https://github.com/pattern-lab/edition-node-gulp.git`
- `cd edition-node-gulp`
- `sudo npm install`
- `gulp patternlab:serve`
- Opened http://localhost:3000/?p=atoms-text-inputs and http://localhost:3000/?p=atoms-select-menu, was unable to maintain <input> focus on click to enter text or <select> focus to select an option.

**Comment by bmuenzenmeyer** [comment]
I've confirmed this behavior - Dave is this happening in PL/PHP too?

**Comment by bmuenzenmeyer** [comment]
I've confirmed this behavior - Dave is this happening in PL/PHP too?

**Comment by bmuenzenmeyer** [comment]
I've confirmed this behavior - Dave is this happening in PL/PHP too?

**Comment by dmolsen** [comment]
This doesn't pop-up on Safari 9.1 hence why I never noticed it. Obviously happening in Chrome. This is a convenience thing as opposed to something that's necessary for PL to work. It ensures that the nav is closed on click even if it that click is inside the iFrame. If can't quickly fix it I'll just comment it out and post it with tonight's release.

**Comment by dmolsen** [comment]
This will be removed tonight. None of my quick attempts to fix it are working.

**Comment by dmolsen** [comment]
This was removed in `v3.1.1`
