### ISSUE TITLE
Check to make sure `comments.comments` exists

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/styleguidekit-assets-default#28]
Also make sure it doesn't equal `null`. Line 127 of `panels-viewer.js` should probably read:

```
if ((comments !== undefined) && (comments.comments !== undefined) && (comments.comments !== null)) {
```

**Comment by bradfrost** [comment]
Closing this out

**Comment by bmuenzenmeyer** [comment]
for history - since I know there is question as to why this was there somewhere in another issue - best of my recollection, it was a PL 1 to PL 2 migration that allowed for backwards compatibility
