### ISSUE TITLE
Is dist/js/patternlab-viewer.min.js used?

### ISSUE THREAD

**Issue by patrikelfstrom** [pattern-lab/styleguidekit-assets-default#30]
What is this file used for? I can't find anything and it's mostly the same as 
dist/styleguide/js/patternlab-viewer.js

**Comment by bmuenzenmeyer** [comment]
You can find it referenced at https://github.com/pattern-lab/styleguidekit-mustache-default/blob/master/views/partials/general-footer.mustache#L55

These repositories work together to support the default PHP and Node frontends.
One could make an argument that both minified and unminified code is not necessary to distribute, but that's a common practice for those that want to understand what code is doing and then use the optimized version in production.

Does this answer your question?

**Comment by patrikelfstrom** [comment]
I'm talking about these three files:

https://github.com/pattern-lab/styleguidekit-assets-default/blob/master/dist/js/patternlab-viewer.min.js
https://github.com/pattern-lab/styleguidekit-assets-default/blob/master/dist/styleguide/js/patternlab-viewer.js
https://github.com/pattern-lab/styleguidekit-assets-default/blob/master/dist/styleguide/js/patternlab-viewer.min.js

The reason I'm asking is because that one js file ends up outside styleguide directory in public. You get something like:

```
public/js/myscript.min.js
public/js/patternlab-viewer.min.js
public/styleguide/js/patternlab-viewer.min.js
```

And I don't want styleguide files amongst my files. But it's not a big issue, I just set it to only include `node_modules/styleguidekit-assets-default/dist/styleguide/` and not `node_modules/styleguidekit-assets-default/dist/` as it is as default in https://github.com/pattern-lab/edition-node-gulp/blob/master/patternlab-config.json

But I was just curious as to why that extra file was there.

**Comment by bmuenzenmeyer** [comment]
This might be a bug in my edition copy logic then. Will take a look when time allows.

**Comment by dmolsen** [comment]
This file has been removed from `dist/`. Bad copy on my part at some point.
