### ISSUE TITLE
Flashes on scroll when viewed on iPhone

### ISSUE THREAD

**Issue by joecarney** [pattern-lab/styleguidekit-assets-default#32]
![pattern_lab](https://cloud.githubusercontent.com/assets/563060/16833391/6f9e65a6-49af-11e6-923c-7613ca1055e2.gif)

Am on iOS9.3.2

This is a screen recording, it shows the flashes as gray boxes, however, on the actual phone, it happens so fast it looks like the screen is just flickering

**Comment by bradfrost** [comment]
Hey @joecarney,
Thanks so much for sharing this. I can't give a timeframe on when this is going to be addressed, but it's definitely on the radar! Thanks again.

**Comment by bradfrost** [comment]
@frostyweather, can you confirm this bug on your iPhone? I'm traveling and would like to either address this or close it out.

**Comment by frostyweather** [comment]
@bradfrost This is happening for me. Wondering if it has to do with the progress bar animation or something.

**Comment by bradfrost** [comment]
Alrighty, @frostyweather and I dove into this, and it has to do with the specific animation used on the [progress pattern](http://demo.patternlab.io/?p=atoms-progress). Once the animation is finished, the flickering goes away and everything behaves normally. We weren't able to reproduce this on any other Pattern Lab project, so closing this out.
