### ISSUE TITLE
Cannot GET ..mustache bug

### ISSUE THREAD

**Issue by mmistakes** [pattern-lab/styleguidekit-assets-default#37]
I recently updated from `3.2.0` to `3.3.0` and noticed something strange in a pattern's info.

The tab name went from **MUSTACHE** to **.Mustache** with an error that it can't locate `..mustache` files.

![screen shot 2016-07-25 at 10 28 29 pm](https://cloud.githubusercontent.com/assets/1376749/17124177/395f4526-52b7-11e6-8e0c-3f5d803b769c.png)

I've observed this happening on Mac OS X and Windows 7. Not sure where the extra `.` in the extension is coming from but locking at the older version `"styleguidekit-assets-default": "3.2.0"` in my `package.json` and installing fixed things for me.

![screen shot 2016-07-25 at 10 23 34 pm](https://cloud.githubusercontent.com/assets/1376749/17124207/6eca06ce-52b7-11e6-856c-3fdf81abfee0.png)

**Comment by bmuenzenmeyer** [comment]
Are you using Pattern Lab Node or PHP? I maintain the Node version and encountered and fixed this bug last night - but have only put it into the `dev` branch so far. I can make a release tonight quick.

**Comment by bmuenzenmeyer** [comment]
Nevermind - package.json is a dead giveaway. I will start the release process now.

If you want to point `patternlab-node` to `pattern-lab/patternlab-node#dev` in  your `package.json` you could confirm this is fixed along with reverting back to 3.3.0 for styleguide-assets-default

**Comment by mmistakes** [comment]
Yes, on the Node version.
Sweet! I just noticed the bug the other day when running `npm update`. Took me a while to figure out which module updated recently and introduced the bug.

**Comment by bmuenzenmeyer** [comment]
`npm update` - https://www.npmjs.com/package/patternlab-node

Give it a shot now and lemme know

**Comment by mmistakes** [comment]
Looks good. All better now!
