### ISSUE TITLE
'View All' menu navigation issue

### ISSUE THREAD

**Issue by hctom** [pattern-lab/styleguidekit-assets-default#41]
Sorry to cross-post this, but https://github.com/pattern-lab/patternlab-php/issues/370 seems to be filed against the wrong repository ;)

So here is the actual issue report by @anthonysimone:

> I just updated patten lab core this morning and noticed the 'View All' items in the navigation were behaving a bit oddly. The 'View All' item on the top level categories (Molecules, Organisms, etc) seems instead to redirect to the last item in the previous menu. So for example, clicking on Organisms -> View All redirects to the last item in the Molecules first level dropdown. However, if you click the same View All link a second time before navigating away from the page, then it does bring you to the All page as expected. I created a new project and tested it in a fresh environment to make sure I didn't just mess up my own project, but I saw the same behavior there as well.

We can confirm this behavior as well on our side.

**Comment by kristianserrano** [comment]
I'm experiencing this exact same issue. I thought I was losing my mind.

**Comment by novascreen** [comment]
Hey, could you guys check if my PR pattern-lab/patternlab-php-core#102 fixes this or whether this is a different, but similar issue?

**Comment by bradfrost** [comment]
@EvanLovely can you investigate?

**Comment by bradfrost** [comment]
This looks like it's closed per https://github.com/pattern-lab/patternlab-php-core/pull/102

Feel free to reopen if this is still an issue.
