### ISSUE TITLE
Support patternengine name rather than file extension in the template tab

### ISSUE THREAD

**Issue by geoffp** [pattern-lab/styleguidekit-assets-default#43]
So, this is to solve my current conundrum, which we touched on in this spec thread: https://github.com/pattern-lab/the-spec/issues/26.

When I present our library of underscore (named as .html, unfortunately) templates, we currently see this unfortunate naming of tabs:

![screen shot 2016-08-22 at 11 49 22 am](https://cloud.githubusercontent.com/assets/76232/17866727/3e376562-686d-11e6-805d-0eed0b55feb6.png)

And we would rather see this much more helpful naming:
![screen shot 2016-08-22 at 11 48 02 am](https://cloud.githubusercontent.com/assets/76232/17866753/5f6c4c7a-686d-11e6-83d1-dabc3d3bec40.png)

To do this, we just need to add one field, `patternEngineName`, to the generated patternData that gets written out onto each rendered template file. I believe we can do this in such a way that it works with both the PHP and Node engine schemes, and also in a way that's backwards compatible should that value not be present.

**Comment by geoffp** [comment]
PR is in for consideration.

**Comment by geoffp** [comment]
@bmuenzenmeyer, can we close this?

**Comment by bmuenzenmeyer** [comment]
I think so, yes
