### ISSUE TITLE
More granular viewport configuration

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/styleguidekit-assets-default#46]
This is a feature request from someone at a company. They'd like to have more control over the ish controls. Rather than selecting ranges, they'd like to do something like:
- iPhone - exactly 320
- Android - exactly 360
- iPad - exactly 768
- L - 768 to 1200
- XL - 1200 to 1800
- Jumbo - 1800 to 3000

You get the idea. I'm not sure what the default ish configurations are, but this was presented to me.

**Comment by bmuenzenmeyer** [comment]
release https://github.com/pattern-lab/styleguidekit-assets-default/releases/tag/v3.5.0 allows users to specify a viewport range for the default S, M, L buttons, including defining an exact size for each.

This doesnt allow users to create more than three, however.
