### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#47]
Upon dropdown navigation, I noticed this error in the console on `3.3.1` and `3.3.0`, though everything seems to still work.

![image](https://cloud.githubusercontent.com/assets/298435/18009256/0798ba2c-6b71-11e6-97f2-2b0aaa349124.png)

**Comment by geoffp** [comment]
@bmuenzenmeyer, when does this occur? On UI load?

**Comment by bmuenzenmeyer** [comment]
@geoffp when I navigate using the dropdown menus

**Comment by bmuenzenmeyer** [comment]
Pulling down edition-node-gulp 100% clean, I do not see this. If no one else experiences this after a couple days I will close as an environment hiccup

**Comment by geoffp** [comment]
👍

**Comment by bmuenzenmeyer** [comment]
This does not appear to occur anymore. Closing.

**Comment by leoacosta** [comment]
@bmuenzenmeyer @geoffp I'm having this issue as well...

**Comment by doige** [comment]
me too. 
php-mustache version.

**Comment by ryanowich** [comment]
I just exprienced the same.

It comes from nav.js which is part of the demo content. 
`navOpen = document.querySelector('.nav-toggle-menu'),`

If you remove the demo nav, you no longer have an element with the class `.nav-toggle-menu`. And therefore `navOpen` is null.

Solution: Don't include nav.js. It's not part of PatternLab core.

**Comment by bmuenzenmeyer** [comment]
good sleuthing @ryanowich 

https://github.com/pattern-lab/starterkit-mustache-demo/blob/master/dist/js/nav.js for those wondering what he is referring to.
