### ISSUE TITLE
What files and data is needed to run this?

### ISSUE THREAD

**Issue by mpdude** [pattern-lab/styleguidekit-assets-default#5]
I'd like to better understand the data and file layout this styleguide kit needs to run.

First, there is (relative to `index.html`) the `styleguide/data/patternlab-data.js` file that needs to initialize some JavaScript vars. I will try to document that, but at the moment it seems it does not need all the data/keys put in there by (for example) patternlab-twig-se.

Then, there are also some hardcoded paths and menu items for the "view all" option; those refer to a `styleguide/html/styleguide.html` file.

`url-handler.js` also contains some hardcoded paths to `styleguide/html/styleguide.html` and `snapshots/index.html` as well as references to a `patterns` directory. I have not yet understood when these come into play. 

I also wonder whether the viewer needs to make assumptions about the organization of patterns into types, subtypes and so on.

Do you guys know about other things?

And – are those assumptions really necessary or do you think we could get away with an extension of `patternlab-data.js` to contain all those paths? 

It could make things much easier for the various PL ports and editions (or custom solutions) if they would generate the files they consider necessary and then just pass data + URLs to the viewer that describe the menu structure as well as paths to the preview files and/or source preview.

**Comment by dmolsen** [comment]
@mpdude -

Submit a PR for your ideal code and we'll look at it. I get what you're saying. This is partly a holdover from old code and only having so much time to clean-up quickly written code.

**Comment by dmolsen** [comment]
I'm not sure we're going to ever get to the point where this is entirely agnostic from PL. It's not meant to be that generic. Honestly, I don't think my code is that great to be worthy of being used in a project agnostic way.
