### ISSUE TITLE
More specific typeahead classes?

### ISSUE THREAD

**Issue by giofilo** [pattern-lab/styleguidekit-assets-default#50]
Hi all,

I'm using Twitter Typeahead in my project. But the css classes in the styleguide are conflicting with my custom styles.

https://github.com/pattern-lab/styleguidekit-assets-default/blob/master/src/sass/styleguide.scss#L587

I would suggest to write or indent the css classes with the"sg-" prefix.

Thank you!

**Comment by bradfrost** [comment]
Pattern Lab's instance of Typeahead is now wrapped in `.pl-c-header` to avoid collisions with user projects.
