### ISSUE TITLE
Configurable size range on S/M/L

### ISSUE THREAD

**Issue by eliland** [pattern-lab/styleguidekit-assets-default#54]
(Feature request)
We tend to use small, medium and large breakpoints in our responsive design projects. Which adds up nicely to PL's S/M/L buttons, _except_ for when it comes to the size range they are set to use. Our breakpoints are usually: small up to 767px, medium 768-1023 and large 1024+. So we would like the S/M/L-buttons to keep within those ranges as well. Today this means fiddling with the go<Small/Medium/Large>() functions, which isn't very practical and is beyond the reach of our versioning system.

Would love to see this range configurable in patternlab-config.json like ishMinimum and ishMaximum is today.

This is probably related to #46 as well, not quite the same, but related.. :)

**Comment by bmuenzenmeyer** [comment]
This feature keeps coming up. @bradfrost I want your input on how important it is, as part of the Pattern Lab spec, to have the S, M, L buttons be randomized. I understand your usecases on #46  and @georgiee  on https://github.com/pattern-lab/patternlab-node/issues/621 but frankly this is:

- not on spec right now, according to the ish methodology. It's an intentionally vague approximation.
- low priority for me compared to PL Node 3.X stuff
- something someone could hack together inside the `styleguide.js` should they need to
- a pretty approachable piece of programming for someone to contribute

**Comment by bmuenzenmeyer** [comment]
[From some ol book I have lying around](http://atomicdesign.bradfrost.com/chapter-3/#viewport-tools-for-flexible-patterns)

> While ish. helps designers and developers uncover bugs along the viewport continuum, I’ve found it to be more helpful as a client and colleague education tool. By building a device-agnostic viewport resizing tool directly into the pattern library, clients and colleagues can come to appreciate the fact that their design system should look and function well no matter the viewport size.

**Comment by bramsmulders** [comment]
Ooof, just read up on all these requests. 
I really do not think you need to sell specific breakpoints to clients, as @georgiee is stating in: [#621](https://github.com/pattern-lab/patternlab-node/issues/621).

The web landscape is not restricted to a finite number of viewport sizes. This is why @bradfrost came up with the idea for `ish`. It's like: "i want to see a small-ish viewport..." This really helps spotting faults in the design on a wide range of viewports. And it is not restricting you to a specific(predefined by the developer) set of best views.

I personally love ish by its simplicity and it helped me fixing a lot of design issues which i never would have found when using predefined breakpoints.

I think its a matter of education: explain why `ish` is working like it is and the client will understand.

**Comment by eliland** [comment]
Just to clarify: I agree with @bramsmulders - I do prefer and want to keep the _randomness_ of `ish` as it is today. It is very helpful in spotting issues both in design and coding long before they go live.

But a few words on breakpoints and clients:
When we go through the design phase with the client it's just not doable to have an infinite number of breakpoints. Instead we define three, four or five of them, design each one while going back and forth with the client before final approval and coding begins. It's not about designing for specific devices or viewports - it's more about limiting the scope to something the client (who may not even know what a pixel is), designer, and developers can all agree on and understand.
As is tradition, we do our coding mobile first and work our way up one breakpoint at a time. Having the SML-buttons match the _range_ between those breakpoints in your design would be an efficiency booster and in fact promote their use. If any one component need some work outside of those common breakpoints, there's nothing stopping us from doing that, and `ish` is helpful in spotting those cases.

**Comment by bmuenzenmeyer** [comment]
being able to specify a range would work for the "exactly this size" use case too, in the sense that you set the M range to `768-768`

Would that work for everyone?

**Comment by bmuenzenmeyer** [comment]
I've tentatively scheduled this for our next open source day

**Comment by bmuenzenmeyer** [comment]
Addressed as part of https://github.com/pattern-lab/styleguidekit-assets-default/releases/tag/v3.5.0
