### ISSUE TITLE
Improve Annotations/Code View Overflow

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#6]
I found a [couple](https://github.com/pattern-lab/patternlab-node/issues/198) [references](https://github.com/pattern-lab/patternlab-php/issues/301) to making this better, but lacking an official home, I am making one here on what I think is the right repo. Close as a duplicate if a better one exists.

Two problems: 
1. A user cannot scroll within the info-viewer to see more annotations
2. A user cannot see the actual pattern, it now being obscured by the info-viewer

![image](https://cloud.githubusercontent.com/assets/298435/14627970/26b1e0ea-05bf-11e6-9fc8-cb188cdb7901.png)

**Comment by dmolsen** [comment]
Right repo. I've marked this as a bug. Thanks.

**Comment by dmolsen** [comment]
I think this issue is dead with the merge of `feature-panels`.

**Comment by bmuenzenmeyer** [comment]
This is still occuring. https://github.com/pattern-lab/patternlab-node/issues/576

**Comment by frostyweather** [comment]
The fix for not being able to scroll to the bottom of the viewport has already been addressed. Here is an animated gif of the proper functionality that is already in develop.
![annotations](https://user-images.githubusercontent.com/13662843/34963271-9bb86a16-fa15-11e7-94e1-9189f9fb1c06.gif)
