### ISSUE TITLE
Make it easier to customize the frontend

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#67]
A bucket of ideas, which may become their own issues in respective repositories, or spec issues:

- [x] Allow users to provide override templates at build time
- [x] Allow users to provide their own CSS at build time
- [x] Do not minify assets by default

**Comment by bradfrost** [comment]
Issue #72 would affect and/or address some of these things.

**Comment by bradfrost** [comment]
I removed minification of the CSS and renamed to `pattern-lab.css` to make it clearer what the file does: https://github.com/pattern-lab/styleguidekit-assets-default/commit/a89f621733e15ee008e7ddb03b3d0a52d6cfe518

**Comment by bradfrost** [comment]
With #72 more or less done, I think these items are addressed. I'm not exactly sure if that includes "Allow users to provide override templates at build time", but I'm going to close this out and we can discuss in a dedicated new issue if that still isn't addressed.

**Comment by bmuenzenmeyer** [comment]
> I'm not exactly sure if that includes "Allow users to provide override templates at build time", but I'm going to close this out and we can discuss in a dedicated new issue if that still isn't addressed.

basically, allow someone to do this inside `patternlab-config.json` https://github.com/pattern-lab/patternlab-node/issues/683 - circumventing the need to fork this repo for simple markup changes (especially if we support a custom CSS file via the `theme` object
