### ISSUE TITLE
Add menu toggle for pattern descriptions from Markdown

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/styleguidekit-assets-default#7]
When a pattern (i.e. `colors.twig`) has a sidecar description file (i.e. `colors.md`), it will show above the pattern, wrapped in a div with a class of `sg-pattern-desc`. It would be great if the menu could have a toggle to show/hide those, right next to Annotations & Code.

![2016-05-06 at 10 43 pm](https://cloud.githubusercontent.com/assets/569699/15090408/033161f6-13dc-11e6-9fc3-ef398de92f8b.png)

**Comment by bradfrost** [comment]
Hey @EvanLovely,
This design and behavior is going to be consolidated a bit. It's going to be combined into a "Show/hide pattern info" label that will expose/hide the pattern info: title, description, code, lineage, annotations. Stay tuned!

**Comment by EvanLovely** [comment]
Sounds good to me; can't wait to see the new hotness!
