### ISSUE TITLE
Deprecate classList.js

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/styleguidekit-assets-default#77]
We're currently using https://github.com/eligrey/classList.js as a polyfill for browsers that don't support `element.classList`. 

Looking at http://caniuse.com/#feat=classlist it's safe to deprecate this.

**Comment by bradfrost** [comment]
I created a new branch of of `feature-css-refactor` that removes the classList polyfill: https://github.com/pattern-lab/styleguidekit-assets-default/commit/7f38590fa0a4bd29730cb94ad591046786ef0d5d

@bmuenzenmeyer, I know you're wheeling and dealing here, so I'll leave it to you to merge this in as you see fit.

**Comment by bmuenzenmeyer** [comment]
so this is ready? i sent an email with a pretty major simplifcation of work.

**Comment by bradfrost** [comment]
This is ready. From now on, I'll use the proper methods!

**Comment by bmuenzenmeyer** [comment]
closed via https://github.com/pattern-lab/styleguidekit-assets-default/releases/tag/v4.0.0-alpha.2

**Comment by illycz** [comment]
classList.min.js file is still linked from template: https://github.com/pattern-lab/styleguidekit-assets-default/blob/develop/src/html/index.html#L72
