### ISSUE TITLE
Ability to resize modal

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/styleguidekit-assets-default#79]
Currently the modal occupies 50% of the screen height:

<img width="1087" alt="screen shot 2017-10-06 at 4 27 20 am" src="https://user-images.githubusercontent.com/383701/31269497-b1254336-aa4e-11e7-81a3-4037f58d04a8.png">

It would be nice to be able to drag the top border of the modal in order to to show more or less information. This would be accomplished with a little handler at the top of the modal, like so:

<img width="1086" alt="screen shot 2017-10-06 at 4 54 18 am" src="https://user-images.githubusercontent.com/383701/31270461-7acccc10-aa52-11e7-905d-5ed4da7380f6.png">

**Comment by sghoweri** [comment]
@bradfrost @bmuenzenmeyer In addition to having the ability to resize the panel vertically (or horizontally... if a layout toggle like in Dev tools was added) I'd strongly suggest we also update the panel to live side by side next to the iFrame viewer itself vs being more like an overlay as it is currently.

Without this, the content being overlapped is inaccessible and not viewable which can further interfere with things like the annotation viewer.

### Before
![image](https://user-images.githubusercontent.com/1617209/31312825-fa21d8f2-ab9c-11e7-8b0e-65f8b968bbdb.png)

### After
![improved pattern lab code viewer](https://user-images.githubusercontent.com/1617209/31312945-9c3fdbb8-aba0-11e7-92e1-cf6b77e97fc3.gif)

With something around these lines in terms of CSS changes -- pre-refactoring and ITCSS classes, and ignoring all these painful ID selectors :(
```
#patternlab-html {
    height: 100%;
}

#patternlab-body {
    display: flex;
    flex-direction: column; // Or flex-direction row to switch to a horizontal layout...
    height: 100vh;
    width: 100vw;
    overflow: hidden;
}

#sg-viewport {
    position: relative;
    height: auto;
    flex-grow: 1;
}

#sg-gen-container {
    height: auto;
    flex-grow: 1;
    display: flex;
    flex-direction: column;
}

#sg-vp-wrap {
    position: relative;
    top: auto;
    flex-grow: 1;
    flex-basis: 100%;
    display: flex;
    flex-direction: column;
    transition: all 0.2s ease;
}

.sg-header {
    position: relative;
}

.sg-modal {
    position: relative;
    height: auto;
    flex-shrink: 1;
    flex-basis: 0;
    flex-grow: 1;
    bottom: auto;
    transition: all 0.2s ease; // @TODO: work through doing this with a 3D transform for better rendering performance
}

.sg-modal.active {
    flex-basis: 300px; //Or whatever resized height
}
```

**Comment by bradfrost** [comment]
@sghoweri that's great stuff, thanks so much for sharing! This has definitely been on the burner for a while, so it's great to see working code to make it happen. The CSS refactor is nearly complete, and once done I'm going to start implementing these features.

**Comment by frostyweather** [comment]
![pattern-panel-resize](https://user-images.githubusercontent.com/13662843/34838027-a07b5ca0-f6ca-11e7-80ce-64b538452080.gif)
Added this within `feature-pattern-info-panel` branch. Here's a gif to show that it is working

**Comment by frostyweather** [comment]
Also as a note, I made the styling of it similar to that of the width resizer. Wasn't sure if we were going to add an svg or anything to these to show that these are resizable or leave them gray and bland on purpose

**Comment by frostyweather** [comment]
This is working in the `feature-pattern-info-panel` branch. Going to close now

**Comment by bmuenzenmeyer** [comment]
Great work @frostyweather - I will merge this asap.
