### ISSUE TITLE
Remove Mustache Code

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/styleguidekit-assets-default#8]
There is Mustache specific code in `src/html/index.html` in both [`master`](https://github.com/pattern-lab/styleguidekit-assets-default/blob/master/src/html/index.html) and [`dev`](https://github.com/pattern-lab/styleguidekit-assets-default/blob/dev/src/html/index.html) branches that is making it's way to the Twig Editions. Even though we have pattern-lab/styleguidekit-twig-default as a styleguidekit that requires this repo, I've not found a way to override what is done in this repo there. I propose one of two solutions:
1. Keep all Template Engine specific code out of this repo and move that job to the Twig/Mustache/etc Engines or to the Twig/Mustache/etc StyleguideKits OR:
2. Provide a way for Engines or StyleguideKits to override what is in this repo; perhaps by providing a template of the same name. 

Perhaps I'm missing a way to do option 2 already. Here is the contents this repos composer.json "extra" section:

``` json
    "extra": {
        "patternlab": {
            "dist": {
                "publicDir": [
                    { "bower_components/*": "styleguide/bower_components/*" },
                    { "css/patternlab/*": "styleguide/css/*" },
                    { "fonts/*": "styleguide/fonts/*" },
                    { "html/index.html": "index.html" },
                    { "images/*": "styleguide/images/*" },
                    { "js/*": "styleguide/js/*" }
                ],
                "sourceDir": [
                    { "css/custom/*": "styleguide/css/*" }
                ]
            },
            "config": {
                "ishMinimum": "240",
                "ishMaximum": "2600",
                "ishControlsHide": ["hay"]
            }
        }
    }
```

Could we use something like this to override the `index.html` file by placing this in the Twig Styleguide's extra section?

``` json
"extra": {
  "patternlab": {
    "dist": {
      "publicDir": [
        { "html/index.html": "index.html" }
      ]
    }
  }
}
```

Thanks!

**Comment by bmuenzenmeyer** [comment]
FWIW - the Node version is also using configurable paths on many assets that get shuffled around for a couple versions now, making consumption simpler. I expect the pattern to work for this repo even too, especially after https://github.com/pattern-lab/styleguidekit-assets-default/pull/4 is supported.

That doesn't address the core concern of mustache being in a shared repo. On the Node side, we have accepted mustache as a PL / front-end dependency, and made all other engines a la carte included atop that. Is that an option for you Evan, at least in the short term? I'd really like to see this repo be stable through WebDesignDay in the end of June, before which I am trying to make a push for Node 2.0-alpha.

**Comment by dmolsen** [comment]
In no way should `index.html` from this repo get consumed by a Pattern Engine. This is entirely front-end and uses [Hogan.js](http://twitter.github.io/hogan.js/) to parse the templates embedded in `index.html`. This is just the viewer/wrapper for PL.

If it's a matter of "no 'mustache' ever in a Twig edition" then you're going to have to develop your own viewer. That's entirely possible. I had to make a choice for a standard renderer on the front-end and it's Hogan. I really don't want to get into Pattern Engines on the front-end. It'd be awesome to say "write your plugin templates this way" and it works wherever.

**Comment by EvanLovely** [comment]
OK, now that I realize it's Hogan.js templates and they're rendering fine and not Mustache templates (even though basically same syntax), we're good! Thought it was a mistake; carry on!
