### ISSUE TITLE
Port all work after 3.2.0 into refactor

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#80]
Building off of https://github.com/pattern-lab/styleguidekit-assets-default/issues/72#issuecomment-334567988

![image](https://user-images.githubusercontent.com/298435/31272766-b0ad1b6a-aa51-11e7-88df-39ef385c76ea.png)

- [x] ~make sure tab is hidden~ brad has changed this logic so I think its ok
- [X] ~update copy of missing description~ likely not needed per https://github.com/pattern-lab/styleguidekit-assets-default/issues/29
- [x] making sure the viewall check happens at position zero
- [x] prefer the display of a pattern engine's name in the template tab 
- [x] ~fix checks for  when view in new window menu item is hidden~ do not see this codepath anymore
- [x] ~add a conditional around "All" button in t op nav so it respect the JSON option to hide it~ shoulld be done proper with #84
- [x] configurable size range

**Comment by bmuenzenmeyer** [comment]
@bradfrost we'll have to methodically port this stuff over. I can take point on it, since it's mostly JS and not design related work

**Comment by bmuenzenmeyer** [comment]
one more change to go

**Comment by bradfrost** [comment]
What tag would fit this issue?

**Comment by bmuenzenmeyer** [comment]
@bradfrost what? oh, label. um not needed. it's done

**Comment by bmuenzenmeyer** [comment]
closed with c1c8b01e2cf66801b66e18881cb0315d704f6a9f
