### ISSUE TITLE
Can no longer drag ish-iframe

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#82]
@bradfrost are you seeing this on the `feature-css-refactor` branch as well?

**Comment by bradfrost** [comment]
All good here, @bmuenzenmeyer. 
![ish](https://user-images.githubusercontent.com/383701/31312247-075efe0c-ab8c-11e7-9e48-07f61313ff8b.gif)

There's a chance I pushed stuff that was still in progress, but in any case this should be smoothed out.
