### ISSUE TITLE
Adjust viewport scrolling when modal is open

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/styleguidekit-assets-default#83]
Adjust the viewport so when the modal window is open, users can still scroll to the bottom of their UI. This #6 and is referenced in #79.

**Comment by frostyweather** [comment]
This has been taken care of. The content will always stay above the panel and the overflow will be scrollable.
![pattern-panel-layout](https://user-images.githubusercontent.com/13662843/34838531-6a8208ea-f6cc-11e7-917c-bdc686e71d12.gif)

**Comment by bmuenzenmeyer** [comment]
Great work @frostyweather - I will merge this asap.
