### ISSUE TITLE
Panel sections have unwanted scrollbars on Windows

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/styleguidekit-assets-default#87]
![image](https://user-images.githubusercontent.com/298435/31370096-91190958-ad4e-11e7-950e-1048376ca497.png)

**Comment by bradfrost** [comment]
Strange, I set `-ms-overflow-style: -ms-autohiding-scrollbar;` for all the appropriate selectors, which is working appropriately in Browserstack. Can you give a bit more context regarding browser version?

**Comment by bmuenzenmeyer** [comment]
Windows 10
Chrome: Version 61.0.3163.100 (Official Build) (64-bit)

also worth noting I am seeing them on the main window too

![image](https://user-images.githubusercontent.com/298435/31442407-f76efd3a-ae5b-11e7-91fc-a5504981cdca.png)
