### ISSUE TITLE
Remove dev branch

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/styleguidekit-assets-default#90]
I noticed there's both a `develop` and a `dev` branch in this repo. `dev` hasn't been updated in a long while. https://github.com/pattern-lab/styleguidekit-assets-default/tree/dev 

Should that be killed?

**Comment by bmuenzenmeyer** [comment]
I was going to last night but there are pending prs that need to be merged
first

**Comment by bmuenzenmeyer** [comment]
deleted
