### ISSUE TITLE
maxViewPortWidth gets overwritten in styleguide.js and prevents Full view

### ISSUE THREAD

**Issue by atu-record** [pattern-lab/styleguidekit-assets-default#98]
as ishViewportRange is defined by default  in 
**pattern-lab/core/config/config.yml.default** on line 48

pressing the full width button in the styleguide always causes to resize maximal to 1200. 

styleguide.js line 24

```javascript
//alternatively, use the ishViewportRange object
if (config.ishViewportRange !== undefined) { 
	minViewportWidth = config.ishViewportRange.s[0];
	maxViewportWidth = config.ishViewportRange.l[1];
}
```

**Comment by bmuenzenmeyer** [comment]
I am having no problems with Pattern Lab Node

my config

``` javascript
    "ishViewportRange": {
      "s": [240, 500],
      "m": [500, 800],
      "l": [800, 2600]
    },
```

clicking `full` brings ish viewport to currentviewport

no ishMaximum defined

**Comment by atu-record** [comment]
@bmuenzenmeyer of course if i define the config, like you did ... it resizes to maximum vieport size. 
but by default i does not work. i guess i does not matter if you use node or php ... its a an styleguide.js issue

**Comment by bmuenzenmeyer** [comment]
fixed via https://www.npmjs.com/package/styleguidekit-assets-default 3.5.2

**Comment by atu-record** [comment]
seems it is not availabe via composer

- The requested package pattern-lab/styleguidekit-twig-default ^3.5 exists as pattern-lab/styleguidekit-twig-default[dev-dev, dev-master, dev-release/3.x, v0.5.0, v0.5.1, v0.5.4, v0.5.5, v0.6.0, v0.6.1, v0.6.2, v0.6.3, v0.6.4, v0.6.5, v2.0.0, v2.0.1, v3.0.0] but these are rejected by your constraint.

**Comment by bmuenzenmeyer** [comment]
styleguidekit-twig-default is not a repo I was aware of until just now. 

this fix was for the official cross-platform mustache assets
